---
image:
  path: https://assets.lilyroger.com/images/trips/2024/scandinavia/scandinavia/sweden-norway-denmark-4x3-1200.avif
  alt: 瑞典斯德哥尔摩机场的尼尔斯骑鹅旅行记；挪威吕瑟峡湾的布道石；丹麦根本哈根的罗森堡城堡。
  width: 1200
  height: 900
  sources:
    - srcset: https://assets.lilyroger.com/images/trips/2024/scandinavia/scandinavia/sweden-norway-denmark-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2024/scandinavia/scandinavia/sweden-norway-denmark-4x3-2400.avif 2400w

layout: article
categories: posts
date: 2024-05-27 00:00:00 +0800
last_modified_at: 2026-09-24 07:15:00 +0800
tags: [2024-Scandinavia, 欧洲, 北欧, 瑞典, 丹麦, 挪威, 徒步, 马拉松]
tagline: 挪威峡湾徒步，瑞典和丹麦初体验
description: 这是我们三十三天的挪威峡湾徒步和北欧三国行的序，这次旅行的重点是徒步挪威峡湾中的“三大奇石”：布道石、奇迹石、巨魔之舌；参加特罗姆瑟的“午夜的太阳马拉松” (Midnight Sun Marathon)；顺路打卡瑞典的斯德哥尔摩，丹麦的哥本哈根和欧登塞。
---
= 斯堪的纳维亚之旅：三十三天挪威峡湾徒步和北欧三国行（序）
:page-liquid: true
:toc: macro
:toclevels: 2
:sectnums:
:imagesdir: https://assets.lilyroger.com/images/trips/2024/scandinavia/scandinavia/

渴望挪威的峡湾徒步已久，我们终于有时间来一次斯堪的纳维亚之旅。这次旅行的重点是挪威**三大奇石**徒步，特罗姆瑟的**午夜的太阳马拉松** (https://msm.no/en/[Midnight Sun Marathon])。顺路打卡瑞典的斯德哥尔摩，丹麦的哥本哈根和欧登塞。

toc::[]

[#plan]
== 计划

我们曾经去过一次挪威。那次探访了松恩峡湾，弗洛姆观光火车，卑尔根和特罗姆瑟。壮阔的峡湾给我们留下了深刻印象。这次有了一个月的时间，终于有机会来一次挪威峡湾的深度游。

挪威的很多徒步线路和必要的相关设施要等到六月份才开放。而且通往目的地之一的**盖朗厄尔**的巨魔之路也要等到六月才开放。特罗姆瑟的午夜的太阳马拉松是在夏至举行。所以我们在挪威的行程很自然的由南向北，先去峡湾徒步，然后去“北极”跑马拉松。

在查询机票的时候，我们发现阿联酋航空进出斯德哥尔摩和哥本哈根的航班相比奥斯陆更具性价比。比如，北京去斯德哥尔摩，然后哥本哈根回北京的全程机票每人不到 5000 元人民币。索性在去挪威之前先去link:{% post_url 2024-05-27-stockholm %}[斯德哥尔摩]玩几天，而离开挪威后再去探访一下根本哈根和欧登塞。算是瑞典和丹麦初体验。

于是就有这次**斯堪的纳维亚之旅**。

[#norway]
== 挪威目标

这次旅行将徒步挪威峡湾的“三大奇石”：

* link:{% post_url 2024-06-02-preikestolen %}[布道石 / 布道台]
* link:{% post_url 2024-06-03-kjeragbolten %}[奇迹石]
* link:{% post_url 2024-06-07-trolltunga %}[巨魔之舌 / 山妖之舌]

还有由南到北四大峡湾中的三个:

* link:{% post_url 2024-05-31-lysefjord %}[吕瑟峡湾]: 徒步胜地，布道石和奇迹石。
* 哈当厄尔峡湾：巨魔之舌，link:{% post_url 2024-06-10-dronningstien %}[王后之路徒步]，举世闻名的link:{% post_url 2024-06-13-hardanger-ciders %}[挪威苹果酒]。
* 松恩峡湾：去过了，这次跳过.
* link:{% post_url 2024-06-12-alesund-geiranger %}[盖朗厄尔峡湾]：高山农场徒步，七姐妹瀑布。

具体的徒步目标包括“三大奇石”徒步，以及精心挑选的另外两个徒步线路。其中**巨魔之舌**和**布道台**徒步绝对是人生目标级别的。这些徒步线路都比较有挑战，加之天气因素，存在个别目标无法完成的可能。所以计划的时候就按照喜爱程度加以排序，必要时放弃某个徒步而确保完成更喜欢的：

[options="header", cols="7,3,2"]
|===
| 徒步 | 峡湾 | 基地

| 巨魔之舌 (Trolltunga) | 哈当厄尔峡湾 | 卑尔根
| 布道石 (Preikestolen) | 吕瑟峡湾 | 斯塔万格
| 奇迹石 (Kjeragbolten) | 吕瑟峡湾 | 斯塔万格
| 王后之路 (Dronningstien) | 哈当厄尔峡湾 | 卑尔根
| 峡湾高山农场 (Skageflå) | 盖朗厄尔峡湾 | 奥勒松
|===

除了徒步之外，自驾大西洋路也是主要目的之一。最后在 6 月 22 日夏至这天，我们选择前往特罗姆瑟参加日不落马拉松，作为挪威之旅的点睛之笔。

[#flights]
== 航班

这次旅行的航班预定相当多。这是一览表:

[options="header", cols="7,5"]
|===
| 航段 | 航司

| 北京 - 迪拜 - 斯德哥尔摩 | 阿联酋航空 (Emirates)
| 斯德哥尔摩 - 奥斯陆 - 斯塔万格 | 北欧航空 (SAS)
| 卑尔根 - 奥勒松 | 维德勒航空公司 (Widerøe)
| 奥勒松 - 特隆赫姆 - 特罗姆瑟 | 维德勒航空公司 (Widerøe)
| 特罗姆瑟 - 奥斯陆 - 哥本哈根 | 北欧航空 (SAS)
| 哥本哈根 - 迪拜 - 北京 | 阿联酋航空 (Emirates)

|===

[#hotels]
== 住宿

三个峡湾，五个徒步，一个马拉松，两个新打卡的国家。这次旅行的行程是颇累了一番心思的。一共提前预定了 14 处住宿地点。下面是我们选择的住宿一览表：

[options="header", cols="4,7,1"]
|===
| 地点 | 住宿 | 晚

| 斯德哥尔摩 | Scandic Klara | 4
| 斯塔万格 | Radisson Blu Atlantic Hotel | 2
| 斯塔万格 | Staysville | 4
| 蒂瑟达尔 (Tyssedal) | Trolltunga Aparthotel | 3
| 洛夫特胡斯 (Lofthus) | link:{% post_url 2024-06-09-hotel-ullensvang%}[Hotel Ullensvang] | 2
| 卑尔根 | Thon Hotel Bristol Bergen | 1
| 奥勒松 | Thon Hotel Ålesund | 1
| 大西洋路 | link:{% post_url 2024-06-14-haholmen-havstuer %}[Håholmen Havstuer] | 2
| 翁达尔斯内斯 | Grand Hotel - by Classic Norway Hotels | 2
| 瓦尔达尔 (Valldal) | Valldal Fjordhotell - by Classic Norway Hotels | 1
| 盖朗厄尔 | Hotel Union Geiranger AS | 2
| 奥勒松 | Thon Hotel Ålesund | 1
| 特罗姆瑟 | Clarion Collection Hotel Aurora | 2
| 哥本哈根 | WIDE Hotel | 5

|===

[#cars]
== 租车

我们在旅行中通常更喜欢公共交通。不过，这次挪威的峡湾徒步之旅中在斯塔万格和奥勒松我们选择了自驾。

* 斯塔万格是徒步布道石，奇迹石的基地。这个区域周日没有公交，而且天气变化快，租车会更容易把握住好天气。
* 奥勒松则毫无疑问要租车。大西洋路，巨魔之路，盖朗厄尔观光公路，都是自驾路线。

[options="header", cols="6,4,2"]
|===
| 地点 | 平台 | 天

| 斯塔万格机场 | 租租车 | 3
| 奥勒松机场 | 租租车 | 7

|===
