---
image:
  path: https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/radisson-collection-strand-hotel-stockholm-4x3-1200.avif
  alt: 位于斯德哥尔摩船岛 (Skeppsholmen) 之上的斯特兰德丽笙精选酒店 (Radisson Collection Strand Hotel, Stockholm)，葛丽泰·嘉宝和英格丽·褒曼的最爱。
  width: 1200
  height: 900
  sources:
    - srcset: https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/radisson-collection-strand-hotel-stockholm-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/radisson-collection-strand-hotel-stockholm-4x3-2400.avif 2400w

layout: article
categories: posts
date: 2024-05-27 12:00:00 +0200
last_modified_at: 2026-10-01 09:15:00 +0800
tags: [2024-Scandinavia, 欧洲, 北欧, 瑞典, 斯德哥尔摩, 城市指南]
tagline: 老城，动物园岛，东城食品市场和地铁站
---
= 斯德哥尔摩攻略：双语地图和最佳景点
:page-liquid: true
:toc: macro
:toclevels: 2
:sectnums:
:imagesdir: https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/
:link-scandinavia: link:{% post_url 2024-05-27-scandinavia %}[斯堪的纳维亚之旅]
:link-gamla-stan: link:{% post_url 2024-05-28-stockholm-gamla-stan %}[斯德哥尔摩老城攻略]
:link-subway-stations: link:{% post_url 2024-05-29-stockholm-subway-stations %}[斯德哥尔摩地铁站攻略]
:link-airport: link:{% post_url 2024-05-27-arn-airport-tranport %}[斯德哥尔摩阿兰达机场攻略]

瑞典的首都斯德哥尔摩 (Stockholm) 是我们{link-scandinavia}的第一站。我们在这里停留四晚，解锁这座曾自称“北欧之都”的城市。老城，动物园岛，东城食品市场，还有人称“世界最长画廊”的斯德哥尔摩地铁站是我们的主要目标。

toc::[]

[#map]
== 双语街区地图

语言障碍是认识斯德哥尔摩这座城市的最大麻烦。瑞典语的地名最初对我们来说与天书无异，所以我们做的第一件事就是准备了一份斯德哥尔摩的双语街区指南地图，聚焦游客最常去的城区部分。

.斯德哥尔摩双语街区指南地图。
image::https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/stockholm-neighborhoods-map-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/stockholm-neighborhoods-map-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/stockholm-neighborhoods-map-4x3-2400.avif 2400w"]

其中，游客最为集中的区域包括：

* 老城 (Gamla Stan)
* 动物园岛 (Djurgården)
* 北城 (Norrmalm)

[#gamla-stan]
== 老城 (Gamla Stan)

老城位于斯德哥尔摩中心的小岛之上，这座始建于 1252 年的小岛是斯德哥尔摩的起源地。广义的老城还包括西边的**骑士岛** (Riddarholmen)，北边的**圣灵岛** (Helgeandsholmen) 和它们之间一座迷你小岛之上的**水流城堡** (Strömsborg )。

老城毫无疑问是斯德哥尔摩游客的首要目的地。除了那些各取所好的博物馆之外，**骑士岛教堂** (Riddarholmskyrkan)，**斯德哥尔摩王宫** (Kungliga slottet)，**大广场** (Stortorget) 等等著名的景点都在这里。参考我们的{link-gamla-stan}。

.斯德哥尔摩老城 (Gamla Stan) 大广场 (Stortorget) 上的标志性彩色建筑。
image::https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/stortorget-gamla-stan-stockholm-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/stortorget-gamla-stan-stockholm-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/stortorget-gamla-stan-stockholm-4x3-2400.avif 2400w"]

[#djurgarden]
== 动物园岛 (Djurgården)

动物园岛在老城的东边。从北城出发，骑自行车需要大约 10 分钟，步行需要大约 30 分钟。动物园岛被称为“博物馆岛”，这里是拥有博物馆、游乐园、水岸、绿地和森林的城市绿洲。

动物园岛的主要目的地是：

* **瓦萨沉船博物馆** (Vasamuseet): 这里收藏了打捞出水的瓦萨号战舰。这艘战舰在 1628 年处女航起航时，炮门打开，所有大炮伸出，然后鸣响了礼炮。结果此时几阵风吹过，战舰就倾侧沉没了。直到 333 年后被打捞出水。
* **斯堪森露天博物馆** (Skansen): 世界上第一座露天民俗博物馆。

.位于斯德哥尔摩动物园岛 (Djurgården) 上的瓦萨沉船博物馆 (Vasamuseet) 展出着打捞出水的瓦萨号战舰。
image::https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/vasamuseet-djurgarden-stockholm-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/vasamuseet-djurgarden-stockholm-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/vasamuseet-djurgarden-stockholm-4x3-2400.avif 2400w"]

[#norrmalm]
== 北城 (Norrmalm)

北城是斯德哥尔摩的市中心，斯德哥尔摩中央车站 (T-Centralen) 就在这里。大多数游客酒店，大型购物中心也集中在北城。著名的步行购物街**女王大街** (Drottninggatan) 纵贯北城，连接着北边的**瓦萨城** (Vasastan) 和南边的**老城** (Gamla Stan)。

**女王还是皇后?** 斯德哥尔摩的 Drottninggatan 购物步行街在 1639 年命名时，是为了向当时年仅 13 岁的瑞典传奇女王**克里斯蒂娜**女王 (Queen Christina) 致敬。她终身未婚，是瓦萨王朝的女性君主，不是皇后。所以，正确的译名应该是“女王大街”，而不是现在中文媒体中常见的“皇后大街”。

.走在女王大街上，你会看到很多狮子造型的水泥路障，它们是真正的反恐英雄，人称“斯德哥尔摩之狮”。
image::https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/lions-stockholm-stockholmslejon-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/lions-stockholm-stockholmslejon-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/lions-stockholm-stockholmslejon-4x3-2400.avif 2400w"]

北城的核心景点有：

* **赛格尔广场** (Sergels Torg): 现代斯德哥尔摩的中心广场，对面的 Åhléns 是斯德哥尔摩最大的购物中心。
* **国王花园** (Kungsträdgården): 亮点是四月中下旬的樱花海，冬季的露天滑冰场。

此外国家博物馆（Nationalmuseum）和瑞典皇家歌剧院（Kungliga Operan）也在北城，而且都在水岸边，与老城隔水相望。

我们选择住在距离中央车站不远的 https://www.scandichotels.se/klara[Scandic Klara] 酒店。在北城主要就是逛街和购物。很多户外用品店以及 Norrøna 的旗舰店就在这里，方便采购挪威峡湾徒步所需的装备。

在北城，我们最喜欢的是俗称“红教堂”的圣詹姆斯教堂 (S:t Jacobs kyrka)，紧邻国王花园，非常出片。

.俗称“红教堂”的斯德哥尔摩圣詹姆斯教堂 (S:t Jacobs kyrka / St James's Church)。
image::https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/st-jacobs-kyrka-james-church-stockholm-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/st-jacobs-kyrka-james-church-stockholm-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/st-jacobs-kyrka-james-church-stockholm-4x3-2400.avif 2400w"]

[#skeppsholmen]
== 船岛 (Skeppsholmen)

在老城、北城和动物园岛之间还有座小岛是**船岛**，名字源于十七世纪这里曾经是瑞典皇家海军基地和造船厂的历史。在船岛的西侧，停靠著名的白色巨型帆船**查普曼号** (Af Chapman)。这艘船完工于 1888 年，如今被改造为一间青年旅舍和咖啡馆。

在船岛东南角，由一座小桥与之相连的迷你岩石小岛是城堡岛 (Kastellholmen)，名字源于岛上的那座**小城堡** (Kastellet)。

船岛和城堡岛都是比较适合漫游和散步的地方。

[#ostermalm]
== 东城 (Östermalm)

从北城出发前往动物园岛时，经过的滨海大道 (Strandvägen) 就在东城。我们在东城的主要目的地是**东城食品市场** (Östermalms Saluhall)，它建于 1888 年，是全球最好的室内食品市场之一，不可错过。此外，夏季每天中午的皇家卫兵换岗仪式，军乐队游行就是从这里的陆军博物馆 (Armémuseum) 出发一直行进到老城王宫广场.

.位于斯德哥尔摩东城 (Östermalm) 的东城食品市场 (Östermalms Saluhall)。
image::https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/ostermalms-saluhall-stockholm-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/ostermalms-saluhall-stockholm-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/ostermalms-saluhall-stockholm-4x3-2400.avif 2400w"]

[#sodermalm]
== 南城 (Södermalm)

南城位于老城南侧，地势较高，生活气息浓厚，是体验瑞典咖啡配甜点的 Fika 慢生活的最佳去处。南城必打卡的是**蒙特留斯路** (Monteliusvägen)，一条水岸边的悬崖步道。这里可以俯瞰老城、市政厅和整个骑士湾 (Riddarfjärden) 的全景，是最佳的日落观景点。

.从老城远眺南城 (Södermalm) 北岸：骑士湾（Riddarfjärden）水面倒映着南城的彩色建筑与悬崖步道。
image::https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/riddarfjarden-sodermalm-stockholm-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/riddarfjarden-sodermalm-stockholm-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/riddarfjarden-sodermalm-stockholm-4x3-2400.avif 2400w"]

[#kungsholmen]
== 国王岛 (Kungsholmen)

北城中央车站向西过桥就是国王岛。这里融合了宏伟的市政建筑、开阔的水岸步道和安静的居民社区。

* **斯德哥尔摩市政厅** (Stadshuset): 坐落在国王岛东南角的红砖建筑，在高塔上的“三王冠”是瑞典的国家象征。每年的诺贝尔奖晚宴在此举行。
* **北梅拉尔水岸步道** (Norr Mälarstrand): 当地人最爱的湖畔步道，也是我们环骑士湾晨跑线路上最喜欢的一段。
* **斯德哥尔摩市政厅地下室餐厅** (Stadshuskällaren): 复刻诺贝尔晚宴菜单的传奇餐厅。

.斯德哥尔摩市政厅地下室餐厅 (Stadshuskällaren) 入口处的青铜雕塑室骑着狮子的酒神和狂欢之神。
image::https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/stadshuskallaren-kungsholmen-stockholm-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/stadshuskallaren-kungsholmen-stockholm-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/stadshuskallaren-kungsholmen-stockholm-4x3-2400.avif 2400w"]

[#riddarfjarden]
== 骑士湾 (Riddarfjärden)

在老城的骑士岛以西、一直到国王岛和南岛之间的**西桥** (Västerbron) 之间的水域就是著名的骑士湾，是斯德哥尔摩最核心的水域。全长约 6.4 公里的骑士湾环线是我们最喜欢的跑步路线。

**是海还是湖？**有趣的是，虽然骑士湾的瑞典语名字 Riddarfjärden 中的 fjärden 的一词和挪威语中的峡湾 fjord 一词同源，但是骑士湾并不是峡湾，甚至都不是海。骑士湾是瑞典第三大淡水湖**梅拉伦湖** (Mälaren) 的一部分，是梅拉伦湖在东边的尽头。越过老城再向东，就属于波罗的海 (Baltic) 的水域了。老城就卡在淡水和咸水之间。

[#drottningholm-palace]
== 皇后岛宫 (Drottningholm Palace)

**皇后岛宫**是被誉为“瑞典凡尔赛”的皇家宫殿。它坐落在市中心以西十多公里，乘坐公共交通需要一小时左右。在 1981 年，现任瑞典国王**卡尔十六世·古斯塔夫**为了让孩子们有较宽敞的庭院，从斯德哥尔摩老城王宫搬到这里，使这里成为瑞典王室的固定居所。其中的中国宫、宫廷剧院和宫廷花园对外开放。

**女王还是皇后？**斯德哥尔摩的 Drottningholm Palace 是 1580 年瑞典国王约翰三世为取悦皇后而命名的；随后的重建扩建也都由皇后主导；如今是现任国王和皇后的私人住所，所以 Drottningholm 是名副其实的“皇后岛”，不同于北城的“女王大街”。

前往皇后岛宫，可以乘坐公共交通，需要 45 分钟左右。不过，最浪漫的方式是去北城西南角，与市政厅隔水相望的 Klara Mälarstrand 码头，乘坐 https://www.stromma.com/en-se/stockholm/dining-cruises/lunch-cruises/drottningholm-palace/[Stromma] 的复古蒸汽游船前往。不论何种方式前往，去皇后岛宫基本上都是需要大半天时间的“市郊一日游”项目。

.在斯德哥尔摩市政厅对面的 Klara Mälarstrand 码头上停靠的“皇后岛号”复古蒸汽轮船 (Drottningholm)。
image::https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/steam-ship-drottningholm-stromma-klara-malarstrand-stockholm-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/steam-ship-drottningholm-stromma-klara-malarstrand-stockholm-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2024/scandinavia/stockholm/steam-ship-drottningholm-stromma-klara-malarstrand-stockholm-4x3-2400.avif 2400w"]

[#metro-stations]
== 斯德哥尔摩地铁站

斯德哥尔摩地铁站被称为“世界最长的画廊”，是斯德哥尔摩最具标志性的网红打卡地之一。如果赶上天气不好，可以去打卡地铁站。斯德哥尔摩的地铁早上5 点开始运营一直到后半夜。其中 T-Centralen 站是中心站，可以去往各条线路。参考我们的{link-subway-stations}。

[#arland-airport]
== 斯德哥尔摩机场

斯德哥尔摩阿兰达机场（Stockholm Arlanda Airport）在市区以北大约 40 公里。如果你是乘飞机抵达的斯德哥尔摩，可以参考我们的{link-airport}。

[#top-attractions]
== 我们的斯德哥尔摩最佳景点

最后，附上我们心目中的斯德哥尔摩的五佳景点。

* 老城
* 瓦萨沉船博物馆
* 地铁站
* 东城食品市场
* 斯堪森博物馆
