---
image:
  path: https://assets.lilyroger.com/images/trips/2026/dolomites/verona-top-attractions/verona-top-attractions-4x3-1200.avif
  alt: 维罗纳 (Verona) 的最佳地点
  width: 1200
  height: 900
  sources:
    - srcset: https://assets.lilyroger.com/images/trips/2026/dolomites/verona-top-attractions/verona-top-attractions-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-top-attractions/verona-top-attractions-4x3-2400.avif 2400w

layout: article
categories: posts
date: 2026-06-19 11:00:00 +0100
date_modified: 2026-06-19 11:00:00 +0100
tags: [2026-Dolomites, 欧洲, 南欧, 意大利, 维罗纳]
tagline: 爱之城，歌剧之乡，小耶路撒冷
---
= 维罗纳 (Verona) 攻略: 12 个最佳景点
:page-liquid: true
:toc: macro
:toclevels: 2
:sectnums:
:imagesdir: https://assets.lilyroger.com/images/trips/2026/dolomites/verona-top-attractions/

维罗纳 (Verona) 有哪些不容错过的景点？当然不仅仅是**朱丽叶的阳台** (Juliet's House)。在这篇攻略中，我们精选了十二个维罗纳的最佳景点，非常适合一两天的行程。

toc::[]

[[most-iconic-landmarks]]
== 标志性的景点

维罗纳最具标志性的两个景点无疑是**朱丽叶之家**和**圆形竞技场**。

[[casa-di-giulietta]]
=== 朱丽叶之家 (Casa di Giulietta)

**朱丽叶之家**无疑是维罗纳最热门的必访景点。

虽然《罗密欧与朱丽叶》只是**莎士比亚**将经典变成不朽的一个爱情故事，但丝毫不妨碍全世界的浪漫主义者把这座中世纪的老房子当作真正的朱丽叶之家，兴致勃勃地来朝圣，在庭院里抚摸**朱丽叶雕像的右胸**，登上**朱丽叶的阳台**打卡。

++++
{% related slugs="verona-juliets-house-guide" %}
++++

如果你热衷于探访罗密欧与朱丽叶的足迹，那么也不要错过市中心南部的**圣弗朗西斯科修道院** (San Francesco al Corso)。这里被认为是劳伦斯神父秘密主持罗密欧与朱丽叶婚礼的地方。修道院的地下室也是**朱丽叶之墓** (Tomba di Giulietta) 的所在地。当然，它实际上是维罗纳市政府为了增加城市魅力而设立的象征性遗址。

[[arena-di-verona]]
=== 圆形竞技场 (Arena di Verona)

建于公元一世纪的**维罗纳圆形竞技场**无疑是这座城市的标志。它比罗马斗兽场更古老，是世界第三大古罗马竞技场。白天可以购票进入内部参观宏伟的结构。而每年夏天在这里举办的**维罗纳圆形竞技场歌剧节** (Arena di Verona Opera Festival) 是全球最大型露天歌剧盛会，是每个歌剧爱好者不容错过的顶级盛事。

维罗纳圆形竞技场歌剧节始于 1913 年，至今已有超过百年的历史。歌剧节 2026 季从六月中旬持续至九月中旬。**威尔第** (Verdi) 和**普契尼** (Puccini) 的六部经典歌剧在此上演，包括**茶花女** (La Traviata) 和**图兰朵** (Turandot) 等等。

可惜音乐节的这些经典剧目基本上都在**每周的四五六上演**，我们的行程恰好完美错过。

[[squares]]
== 广场

维罗纳的核心广场是是**百草广场** (Piazza delle Erbe) ，最大的广场则是**布拉广场** (Piazza Bra) ，当地人称为**但丁广场**的**领主广场** (Piazza dei Signori) 紧邻百草广场，同样不容错过。

[[piazza-delle-erbe]]
=== 百草广场 (Piazza delle Erbe)

**百草广场**是维罗纳最古老、最繁华的广场，建立在古罗马广场 (Forum) 的遗址之上，从那时起就是这座城市的心脏。百草广场中心常年设有市集摊位，这种传统已经延续了数百年。

狭长的百草广场上的看点有很多：

* **马费宫** (Palazzo Maffei): 百草广场北侧最漂亮的巴洛克式建筑，如今是座私立博物馆。马费宫屋顶上装饰着六尊希腊神像。其中右侧的五座雕像都是十七世纪建造宫殿时，用维罗纳红大理石雕刻的；最左侧的大力神**赫拉克勒斯**是唯一的白色大理石雕像，据信是在挖掘宫殿地基时发现的一件古罗马文物，被当时的马费家族直接安放在此。

* **加尔代洛塔** (Torre del Gardello): 紧邻马费宫的砖塔。由**斯卡利杰里**家族第四代统治者**坎西尼奥里奥** (Cansignorio) 下令建造的，于 1370 年完工。塔高 44 米，在当时是维罗纳最高的建筑，直到后来被邻近的兰贝蒂塔 (Torre dei Lamberti) 超越。塔顶有中世纪风格的**双连拱窗**和**雉堞**（齿状装饰），燕尾形的齿也宣示了对**神圣罗马帝国皇帝**的效忠（凸凹的矩形齿，代表效忠教皇）。

* **圣马可之柱** (Colonna di San Marco): 这根大理石柱立于 1523 年。当时维罗纳属于威尼斯共和国的领土，威尼斯人习惯在每个属地的核心广场竖起“圣马可翼狮”（共和国的象征）宣誓主权。不过这根柱子上的翼狮在 1797 年拿破仑占领维罗纳时被毁，现在看到的是 1886年重新制作补上的。

* **维罗纳圣母喷泉** (Fontana di Madonna Verona): 广场中心著名的圣母喷泉，由**斯卡利杰里**家族第四代统治者**坎西尼奥里奥** (Cansignorio) 下令建造的。雕像身体是公元四世纪的古罗马文物，而头部和手臂是建造喷泉时加上的。虽然名为“圣母”，但她实际上是维罗纳这座城市的拟人化象征，并不是那个宗教人物。

* **石亭** (Berlina): 广场中央的一个带顶棚的四柱大理石小亭子。在中世纪和文艺复兴时期，这个亭子有很多作用，新官宣誓、宣读法令、罪犯示众等等。出了这些，它还有一个有趣的作用，那就是**度量衡标准**。石亭的柱子上刻有线条，代表了当时的长度标准；台阶上刻有凹槽，这是用来测量粮食、橄榄、豆子等散装物资的官方容器标准。

* **市场之柱** (Colonna del Mercato): 与广场北侧的圣马可之柱呼应，广场南侧有一根维罗纳红大理石柱，柱顶是一个非常精致的哥特式小神龛。神龛的四个面都有壁龛，里面雕刻着精美的浮雕人像。其中一个是维罗纳的主保圣人**圣芝诺** (San Zeno)，形象是一名持鱼竿的主教。
+
这根市场之柱建于米兰**维斯孔蒂**家族 (Visconti) 统治时期的 1401 年，因此也称为**维斯孔蒂支柱**。

* **贝托·巴尔巴尼**的雕像 (Berto Barbarani): 在广场的最南端，靠近卡佩罗路 (Via Cappello) 的入口处，有一尊雕像，他是维罗纳最受爱戴的本地诗人，百草广场是他创作的灵魂源泉。

* **肋骨拱门** (Piazza delle Erbe): 在香草广场通往旁边的领主广场 (Piazza dei Signori) 的拱门 (Arco della Costa) 下，悬挂着一根巨大的鲸鱼肋骨。

[[piazza-bra]]
=== 布拉广场 (Piazza Bra)

布拉广场 (Piazza Bra) 是意大利维罗纳 (Verona) 面积最大的广场，也是意大利乃至欧洲最宏伟的广场之一。维罗纳圆形竞技场 (Arena di Verona) 正是坐落在这座广场之上。广场名字 Bra 源于 Braida 一词，意思是“宽阔的空地”。在罗马时代，这里曾是城墙外的一片荒地；中世纪时曾作为木材、干草和牲畜市场。

除了圆形竞技场，布拉广场上的看点还有：

* **利斯顿漫步道** (Liston)：广场西侧是一条铺设着维罗纳红大理石的宽阔人行道。这里遍布着带有露台的咖啡馆、餐厅和优雅的古建筑，是当地人聊天、喝咖啡、看风景的社交圣地。

* **中央花园**：广场中心有一片绿意盎然的花园，矗立着意大利国父国王**维托里奥·艾曼纽二世**的骑马雕像。花园内的喷泉被称为“阿尔卑斯喷泉”，是为纪念维罗纳与德国慕尼黑结为友好城市而建。

* **布拉大门** (Portoni della Bra)：布拉大门是古代进入市中心的关卡，由两个巨大的中世纪拱门组成，门上嵌有一个老时钟。在大门一侧的城墙上，设立了一尊莎士比亚的半身像，旁边有一块牌匾，铭文上的是《罗密欧与朱丽叶》第三幕第三场中的一段台词：“维罗纳城墙之外没有世界，只有炼狱、苦刑、甚至地狱。因此，从这世界被放逐就是从世界被驱逐，而世界的放逐便是死亡。”

[[piazza-dei-signori]]
=== 领主广场 (Piazza dei Signori)

**领主广场** (Piazza dei Signori) 通常被当地人称为**但丁广场**，它是维罗纳最优雅、最具贵族气息的广场。距离百草广场仅有几步之遥，穿过**肋骨拱门**下面的小巷就到了。之所以被称为 但丁广场，是因为广场中央矗立着伟大诗人 但丁 (Dante Alighieri) 的大理石像。但丁 在被佛罗伦萨放逐期间，曾在维罗纳的 **斯卡利杰里** 家族的庇护下，在这里生活了七年。这段时期是他创作的高峰期。

领主广场上其它的看点包括：

* **理性宫** (Palazzo della Ragione): 有时也音译作**拉吉奥内宫**。意大利语 Ragione 意为“理性”、“理智”或“法理”。中世纪时期，这里是维罗纳的法院所在地。穿过拱门进入宫殿内部，是一个迷人的**旧市场院子** (Cortile del Mercato Vecchio)。这里隐藏着用维罗纳红大理石建造的**领主阶梯** (Scala della Ragione)，它建于十五世纪，是意大利现存最完美的晚期哥特式阶梯之一，也是维罗纳最佳摄影点之一。

* **议会凉廊** (Loggia del Consiglio): 这是意大利最精美的早期文艺复兴建筑之一，同样建于十五世纪，最初是作为市政厅所在地而建。底层是由八个圆拱组成的敞开式走廊，屋顶上装饰着古罗马时期维罗纳最杰出的五位名人雕像。

* **执政官宫** (Palazzo del Podestà): 领主广场上上历史最为厚重的建筑之一。白色的正门上有代表威尼斯共和国统治的翼狮，顶部燕尾形的**雉堞**。最初这里叫**康格兰德宫** (Palazzo di Cangrande)，是**斯卡利杰里**家族第二代统治者，也是最伟大统治者**康格兰德一世**的住所。诗人但丁在维罗纳流亡时也是住在这里。如今是维罗纳省政府所在地。

* **斯卡利杰里家族墓地** (Arche Scaligere): 从执政官宫旁的拱门穿过去，映入眼帘的宏伟哥特式建筑群就是曾统治维罗纳的**斯卡利杰里**家族的墓地，而旁边就是**圣玛丽亚安提卡教堂** (Santa Maria Antica)，这个家族的教堂。教堂侧门上方的就是康格兰德一世 (Cangrande I) 的石棺，顶上就是他著名的**微笑骑马雕像**（复制品，原件收藏在老城堡博物馆中）。此外，四角凉亭的那一座是第三代主要统治者**马斯提诺二世** (Mastino II) 之墓；那座六角形的则是第四代统治者**坎西尼奥里奥** (Cansignorio) 之墓。有趣的是，这三位统治者名字的字面意思分别是“大狗“ (Cangrande)、“獒” (Mastino) 和“领主之犬” (Cansignorio)。

在领主广场的理性宫的外墙上，你还能找到类似威尼斯 (Venice) 的，被称为“狮子之口” (Bocche Di Leone / Lions' Mouths) 的秘密举报信箱。你知道在哪里吗？

++++
{% related slugs="verona-bocche-di-leone" %}
++++

[[panorama-view]]
== 全景观景点

维罗纳最佳的全景观景点有两处，老城中心的**朗贝尔蒂塔** (Torre dei Lamberti)，以及老城外的**圣彼得城堡观景台** (Piazzale Castel San Pietro)。

[[torre-dei-lamberti]]
=== 朗贝尔蒂塔 (Torre dei Lamberti)

**朗贝尔蒂塔** (https://www.torredeilamberti.it/en/[Torre dei Lamberti]) 是维罗纳最高的塔楼，耸立在百草广场旁，距离朱丽叶的阳台近几步之遥。登上朗贝尔蒂塔顶可欣赏维罗纳全景。

朗贝尔蒂塔 高 84 米，由两个风格不同的部分组成：下部的墙体上砖块和凝灰岩块交替排列，形成规则的条带，历史可以追溯至十二世纪；而上部则完全由砖块建造，其历史可以追溯到十五世纪下半叶。游客可以选择塔内的 368 级台阶攀登至全景露台和钟楼，也可以乘坐电梯节省体力。

攀登 朗贝尔蒂塔 需要购票，可以在塔楼底部的售票处直接购买，全价票是 6,00 € (2026)。参观票中还包含了旁边的 **阿基莱·福蒂现代艺术馆** (Galleria d'Arte Moderna Achille Forti) 以及其中精美的巴洛克风格的 **公证人礼拜堂** (La Cappella dei Notai)。

维罗纳城市旅游卡 (Verona Card) 中包含了 朗贝尔蒂塔 的门票。

[[ponte-pietra]]
=== 圣彼得城堡观景台 (Piazzale Castel San Pietro)

**圣彼得城堡观景台** (Piazzale Castel San Pietro) 是欣赏维罗纳全景的最佳地点，提供了如同明信片般的视角，可以清晰地看到**阿迪杰河** (Adige) 蜿蜒穿过古城的壮丽景色（圣彼得城堡内部目前不对公众开放）。

欣赏维罗纳城市全景的最佳时间是日落前，此刻夕阳将城市染成金色，是公认的最浪漫时刻。

圣彼得城堡坐落在阿迪杰河左岸的 **圣彼得山** 之上。从老城区经 **彼得拉桥** (Ponte Pietra) 穿过阿迪杰河，在桥头左侧有条石阶小巷，徒步上山只需要大约 15 分钟。

不想爬山的话，石阶的位置继续向左可以找到上山的缆车站。乘坐**缆车** (https://www.funicolarediverona.it/en/ticket-office/[Funicolare di Castel San Pietro]) 往返，单程只要几分钟，往返票价是 3 欧元。

圣彼得城堡的正下方，座落着罗马剧场考古博物馆 (Museo Archeologico al Teatro Romano)，门票包含在 Verona Card 里。时间充裕的话，可以顺路逛逛。

连接老城区与圣彼得城堡和罗马剧院的彼得拉桥是维罗纳现存唯一的**古罗马桥梁**，始建于公元前一世纪。桥拱中白色大理石部分是最初的古罗马遗存；红砖部分则是中世纪**斯卡利杰里**家族 (Scaligeri / Scala) 统治时期加固和重修的痕迹。

二战中，撤退的德国军队炸毁了维罗纳所有的桥梁。战后，维罗纳市民从阿迪杰河底打捞起炸碎的石块，按照“原样、原位、原石”的原则，像拼图一样精心修复了这座桥。

彼得拉桥名字中的 Pietra 的意思就是“石头”。而圣彼得被誉为基督教的“磐石”，他的名字就源于“石头”一词。

[[museums]]
== 艺术博物馆

维罗纳最具代表性的艺术博物馆就是**老城堡博物馆** (Museo di Castelvecchio)。

[[castelvecchio-museum]]
=== 老城堡博物馆 (Museo di Castelvecchio)

**老城堡博物馆** (Museo di Castelvecchio) 是维罗纳最重要的艺术博物馆之一，位于由维罗纳中世纪统治家族**斯卡利杰尔**家族 (Scaligeri / Scala) 兴建的一座军事堡垒中。该博物馆因其卓越的历史艺术收藏，以及意大利建筑大师卡罗·斯卡帕 (Carlo Scarpa) 在上世纪进行的划时代改造而闻名于世。

老城堡的建造者**康格兰德二世** (Cangrande II) 非常残暴，被民众称为“疯狗”（还记得吗？他本名的字面意思就是“大狗”）。为了防范城内市民起义，才修建了老城堡。通过跨越**阿迪杰河**的老城堡桥，确保在紧急情况下能迅速向北撤退。讽刺的是，康格兰德二世最后不是死于市民之手，而是被亲弟**坎西尼奥里奥** (Cansignorio) 当众刺杀的。

历史上的**坎格兰德一世** (Cangrande I della Scala, 1291-1329) 是维罗纳最辉煌的黄金时代的缔造者和城市之父，是这座城市的象征。珍藏在老城堡博物馆的**坎格兰德一世的骑马雕像是维罗纳最重要的艺术瑰宝之一。雕像最独特之处在于他脸上神秘的咧嘴微笑，这在当时的墓葬雕像中极为罕见。

老城堡博物馆还收藏有 皮萨内洛 (Pisanello) 的《圣母与鹌鹑》 (Madonna della Quaglia) 木板蛋彩画，极具辨识度，是国际哥特式风格的巅峰之作。此外还有 曼特尼亚，乔瓦尼·贝利尼 (Giovanni Bellini)，提香，委罗内塞 等大师的作品。

连接老城堡的老城堡桥，也叫 **斯卡利杰罗桥** (Ponte Scaligero) ，和 **彼得拉桥** (Ponte Pietra) 一样在二战中被德军炸毁。维罗纳人从阿迪杰河底打捞出了几乎所有被炸落的红砖和石块，极其严谨地原样重建了这座桥。

[[churches]]
== 教堂

维罗纳最重要的教堂包括 **维罗纳大教堂** (Duomo di Verona) 和 **圣阿纳斯塔西娅大教堂** (Basilica di Santa Anastasia)。

[[duomo-di-verona]]
=== 维罗纳主教座堂 (Duomo di Verona)

**维罗纳主教座堂** 并非单一的教堂，而是一组由多个历史建筑组成的建筑群，即 **维罗纳主教座堂建筑群** (Complesso del Duomo di Verona)。

建筑群的主体是主教座堂，展现了从罗曼式到哥特式，再到文艺复兴和巴洛克风格的演变。正立面中央的罗曼式大门由粉白相间的大理石建成，两侧有守卫的狮子和圣经场景浮雕；哥特式的玫瑰窗则是在十四世纪翻修时加入的。

在主教座堂的内部左侧第一个礼拜堂中，收藏着 **提香** (Titian / Tiziano Vecellio) 的《圣母升天》(Assunta / Assumption of the Virgin, 1535)。由于 提香 1518 年的的成名作，威尼斯版的《圣母升天》被誉为“威尼斯画派第一杰作”，维罗纳的这幅“简约版”《圣母升天》长期处于从属地位。但它是 提香 在维罗纳的唯一真迹，而且原址保存在主教座堂，不容错过。

在主教座堂后部，**圣约翰洗礼堂** (San Giovanni in Fonte) 是罗曼式建筑的杰作。这个圣约翰指的是施洗者圣约翰，而不是十二使徒之一的使徒圣约翰。意大利语 Fonte 的意思就是“泉水”或者“洗礼池”。圣约翰洗礼堂核心看点是中心的巨大八角形洗礼池，由单块维罗纳红大理石雕刻而成，上面刻有精美的圣经故事浮雕。

**圣海伦娜教堂** (Chiesa di Sant'Elena) 与洗礼堂相邻，这是建筑群中最古老的部分。在教堂地板下，你可以透过玻璃看到保留至今的四世纪马赛克地砖。

在主教座堂前的广场一侧，紧邻阿迪杰河的是 **参事会图书馆** (Biblioteca Capitolare)。被认为是世界最古老且仍在使用的图书馆，其历史可追溯至公元五世纪。馆内保存了约 1200 册手抄本和 11000 份羊皮卷等稀世珍藏，堪称欧洲文化宝库。中世纪文豪 **但丁 (Dante Alighieri) **和 **彼特拉克** (Francesco Petrarca) 都曾在这里查阅文献并进行研究。

[[basilica-di-santa-anastasia]]
=== 圣阿纳斯塔西娅大教堂 (Basilica di Santa Anastasia)

**圣阿纳斯塔西娅大教堂** 是维罗纳最大的教堂，是意大利哥特式风格的杰出代表。教堂内部拥有极高的穹顶和由**维罗纳红大理石**柱支撑的中殿。

这里的核心看点是文艺复兴早期巨匠 **皮萨内洛** (Pisanello) 的湿壁画《圣乔治与公主》 (_Saint George and the Princess_) 。它是国际哥特式风格在意大利最重要的代表作，位于 **佩勒格里尼礼拜堂** (Pellegrini Chapel) 入口拱门上方的外墙上。壁画左侧的龙已经损毁了，只剩下右侧的圣乔治与公主。

圣阿纳斯塔西娅大教堂 的另一个看点是入口处的两个著名的圣水池，基座是两个弯腰支撑的驼背人雕塑，民间传说触摸他们的背部会带来好运。其中左边那个背负着圣水盆、表情痛苦的的驼背人出自维罗纳最著名的艺术家 **保罗·委罗内塞** (Paolo Veronese) 的父亲，身为石匠的 **加布里埃尔·卡利亚里** (Gabriele Caliari) 之手。

[[pedestrian-commercial-street]]
== 步行街

如果你喜欢逛步行商业街，维罗纳的 **马志尼大道** 就是了。

[[via-giuseppe-mazzini]]
=== 马志尼大道 (Via Giuseppe Mazzini)

**朱塞佩·马志尼** (Giuseppe Mazzini) 是意大利统一运动的精神领袖，与外交大师 **加富尔** (Cavour) 和“两个世界的英雄” **加里波第** (Giuseppe Garibaldi) 被尊为“建国三杰”。以他的名字命名的 **马志尼大道** 连接着维罗纳两个最核心的广场，即 **圆形竞技场** (Arena) 所在的 **布拉广场** (Piazza Bra) 和 **朱丽叶阳台** 旁的 **百草广场** (Piazza delle Erbe)，是维罗纳首屈一指的步行商业街。

这条步行街铺设的粉红色大理石就是著名的维罗纳红大理石 (Rosso Ammonitico)。这里是全城寻找来自侏罗纪的菊石 (Ammonites) 化石的最佳地点之一。建议清晨打卡，此时游客还没有涌进来，路面刚刚冲洗完，光洁的大理石纹理清晰，非常适合拍摄。

[[garden]]
== 园林

如果你想在维罗纳市区内寻找一处宁静且充满历史感的地方，**朱斯蒂花园** 是首选。

=== 朱斯蒂花园 (Giardino Giusti)

朱斯蒂花园是欧洲最美的文艺复兴时期的园林之一，位于阿迪杰河对岸的 **小维罗纳** (Veronetta) 区从维罗纳的历史中心穿过阿迪杰河上的 **新桥** (Ponte Nuovo) 后不远，就可以到达 **朱斯蒂宫** 的大门处。在这里购票后，首先进入的是朱斯蒂宫，快速浏览建筑内部后，进入朱斯蒂花园。

朱斯蒂花园 的核心是始建于 1786 年的树篱迷宫，是欧洲现存为数不多的、至今仍保持原貌的文艺复兴式树篱迷宫之一。虽然它在二战期间受损，但在战后按照原图纸进行了精准的修复。

花园的中央是一条笔直的柏树大道，从建筑通往对面的山坡。在柏树大道的尽头，就是著名的**大面具** (Il Mascherone) 露台。一个表情狰狞、张着大嘴的巨大石雕面具，嵌在石崖上。

位于大面具右侧的小石塔内，有一条螺旋楼梯，由此可以登上大面具正上方的观景台 (Il Belvedere)。这是花园的最高点。站在这里，你可以俯瞰迷宫的完美几何构图，并能远眺维罗纳历史中心。

参观朱斯蒂花园需要两小时左右。全价票 14 欧元，持有 Verona Card 维罗纳卡可享受优惠价 9 欧元。