---
image:
  path: https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-arena-4x3-1200.avif
  alt: 维罗纳红大理石 (Red Verona Marble / Rosso Ammonitico) 中来自侏罗纪的菊石 (Ammonites) 化石。
  width: 1200
  height: 900
  sources:
    - srcset: https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-arena-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-arena-4x3-2400.avif 2400w

layout: article
categories: posts
date: 2026-06-17 16:00:00 +0200
last_modified_at: 2026-09-14 08:20:00 +0800
tags: [2026-Dolomites, 欧洲, 南欧, 意大利, 维罗纳]
tagline: 来自侏罗纪的“阿蒙之角”
description: 在维罗纳 (Verona) 随处可见一种粉红色的大理石，它们就是维罗纳红大理石 (Red Verona Marble / Rosso Ammonitico)。你还会发现其中有许多鹦鹉螺形状的古生物化石，它们是来自侏罗纪的古生物化石菊石 (Ammonites)。
---
= 维罗纳红大理石：寻找侏罗纪的菊石化石 (Ammonites)
:page-liquid: true
:toc: macro
:toclevels: 2
:sectnums:
:imagesdir: https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/

在维罗纳的圆形竞技场中，大教堂里，甚至人行道上，你都会看到一种粉红色的大理石。他们就是著名的**维罗纳红大理石** (Red Verona Marble / Rosso Ammonitico)。稍加留意，你还会发现其中有许多大小不一的螺旋状的古生物化石，他们是来自侏罗纪的菊石 (Ammonites) 化石。

toc::[]

[[ammonites]]
== 菊石

菊石是一种已经灭绝的海生无脊椎动物，和现在的章鱼、乌贼是远亲，但长着类似鹦鹉螺的外壳。它们在地球上生存了几亿年，直到侏罗纪与恐龙同时灭绝。菊石化石表面的纹理像菊花瓣一样复杂，这也是其中文名的来源。

菊石的英文名 Ammonite 和意大利语名字 Ammonitico 来源于古埃及主神**阿蒙** (Ammon)。古埃及的神好多都是人身动物头，主神阿蒙神就是人身公羊头。到了古罗马时期，阿蒙神又与罗马神话中的主神朱庇特（也就是希腊神话中的宙斯）结合成了**朱庇特·阿蒙**神 (Jupiter Ammon)，其形象通常是一个男性的头上长着一对向后弯曲、呈螺旋状的羊角。

.维罗纳马费阿诺石刻博物馆 (Museo Lapidario Maffeiano) 中的朱庇特·阿蒙神 (Jupiter Ammon) 头像。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/jupiter-ammon-museo-lapidario-maffeiano-verona-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/jupiter-ammon-museo-lapidario-maffeiano-verona-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/jupiter-ammon-museo-lapidario-maffeiano-verona-4x3-2400.avif 2400w"]

在公元一世纪，古罗马著名的博学家老普林尼 (Pliny the Elder) 在其巨著《博物志》中，首次提到了这种螺旋形的化石，并称之为“阿蒙之角”。

[#verona-red-marbles]
== 维罗纳红大理石

侏罗纪时期，维罗纳所在的位置曾是一片海洋，海底沉积了厚厚的泥沙和贝壳。后来，地球板块碰撞，形成了数座山脉，其中包括维罗纳北部的**巴尔多山** (Monte Baldo) 和**莱西尼山脉** (Lessinia) 。维罗纳随处可见的粉色和红色大理石就来自于这些地区。

严格来说，维罗纳红大理石从地质学上讲其实是石灰岩。不过维罗纳的大理石工匠不这么认为，他们坚持称之为大理石。维罗纳许多地方和建筑都使用了红色大理石，几乎无处不在。

[#hunting-ammonites]
== 寻找菊石化石

在维罗纳哪里可以找到又大又漂亮的菊石呢？

[#piazza-erbe]
=== 香草广场 (Piazza Erbe)

在香草广场的白色大理石亭附近就能找到很漂亮的菊石化石。

.维罗纳香草广场 (Piazza Erbe) 上的菊石化石。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-piazza-erbe-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-piazza-erbe-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-piazza-erbe-4x3-2400.avif 2400w"]

[#duomo-di-verona]
=== 维罗纳大教堂 (Duomo di Verona)

在大教堂后方的圣约翰洗礼堂 (San Giovanni in Fonte) 中心有一个巨大的八角形洗礼盆，由整块维罗纳红大理石雕凿而成，上面刻有极为精美的《基督的一生》浮雕。在洗礼盆的台阶上，可以找到又大又完整的的菊石化石。

.维罗纳大教堂 (Duomo di Verona) 中的菊石化石。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-duomo-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-duomo-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-duomo-4x3-2400.avif 2400w"]

[#basilica-di-santa-anastasia]
=== 圣安那斯塔西亚教堂 (Basilica di Santa Anastasia)

在圣安那斯塔西亚教堂中，地面上有独特的大理石镶嵌。在靠近入口一侧的中央，可以找到红大理石中完整的菊石化石，极具辨识度。

.维罗纳圣安那斯塔西亚教堂 (Basilica di Santa Anastasia) 中的菊石化石。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-santa-anastasia-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-santa-anastasia-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-santa-anastasia-4x3-2400.avif 2400w"]

[#via-giuseppe-mazzini]
=== 马志尼路 (Via Giuseppe Mazzini)

**马志尼路**是连接**香草广场** (Piazza delle Erbe) 和**布拉广场** (Piazza Bra)的狭长步行街，是维罗纳首屈一指的购物街。这里的粉色大理石地砖是全城抛光度最高的，最清晰的巨型菊石位于街道南端，靠近圆形竞技场的一侧。下雨后或是清晨街道刚清洗过时，大理石的颜色最鲜艳，非常适合拍摄。

.维罗纳马志尼路 (Via Giuseppe Mazzini) 上的菊石化石。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-via-giuseppe-mazzini-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-via-giuseppe-mazzini-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-via-giuseppe-mazzini-4x3-2400.avif 2400w"]

[#basilica-di-san-zeno-maggiore]
=== 圣泽诺大教堂 (Basilica di San Zeno Maggiore)

目标是圣泽诺大教堂大门外的台阶。这里的红色大理石年代久远，色泽深沉（呈砖红色），其中的菊石化石由于含铁量不同，颜色往往比周围岩石更深，对比度非常高，清晰度极佳。

.维罗纳圣泽诺大教堂 (Basilica di San Zeno Maggiore) 大门外台阶上的菊石化石。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-san-zeno-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-san-zeno-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-san-zeno-4x3-2400.avif 2400w"]

[#arena-di-verona]
=== 圆形竞技场 (Arena di Verona)

建于公元一世纪的维罗纳圆形竞技场无疑是这座城市的标志。它比罗马斗兽场更古老，是世界第三大古罗马竞技场。在竞技场的看台台阶上，可以找到很多的菊石化石。我们尤其喜欢这里的菊石化石，很多都是立体有厚度的。

.维罗纳圆形竞技场 (Arena di Verona) 看台台阶上的菊石化石。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-arena-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-arena-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-arena-4x3-2400.avif 2400w"]

[#scala-della-ragione]
=== 理性阶梯 (Scala della Ragione)

维罗纳理性宫 (Palazzo della Ragione) 的理性阶梯由维罗纳红大理石建成，台阶和扶手中有大量密集的菊石化石。不过这里的菊石化石多数都不完整了。需要耐心才能找到比较好的。

.维罗纳理性阶梯 (Scala della Ragione) 上的菊石化石。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-scala-ragione-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-scala-ragione-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-scala-ragione-4x3-2400.avif 2400w"]

[#ponte-pietra]
=== 彼得拉桥 (Ponte Pietra)

维罗纳最古老的彼得拉桥 (Ponte Pietra)，本身就是一座“化石博物馆”。桥面和护栏铺设的巨大石块，桥砖常年被雨水冲刷和行人踩踏，许多菊石化石自然风化出来，立体而有厚度，不难发现。

.维罗纳彼得拉桥 (Ponte Pietra) 桥面上的菊石化石。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-ponte-pietra-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-ponte-pietra-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-ponte-pietra-4x3-2400.avif 2400w"]

[#corso-porta-borsari]
=== 波萨利门大道 (Corso Porta Borsari)

波萨利门大道是维罗纳老城区内一条非常著名的历史商业步行街。它连接着市中心的香草广场与雄伟的古罗马城门**波萨利门** (Porta Borsari)。这条大道两侧的白色大理石地面上可以找到很多巨大的菊石化石。

.维罗纳波萨利门大道 (Corso Porta Borsari) 地面上的菊石化石。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-corso-porta-borsari-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-corso-porta-borsari-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-red-ammonites/verona-red-ammonites-corso-porta-borsari-4x3-2400.avif 2400w"]
