---
image:
  path: https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-portal-4x3-1200.avif
  alt: 维罗纳大教堂 (Duomo di Verona) 也是维罗纳的主教座堂 (Cattedrale)。
  width: 1200
  height: 900
  sources:
    - srcset: https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-portal-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-portal-4x3-2400.avif 2400w

layout: article
categories: posts
date: 2026-06-17 16:30:00 +0200
last_modified_at: 2026-09-22 20:45:00 +0800
tags: [2026-Dolomites, 欧洲, 南欧, 意大利, 维罗纳, 教堂, 艺术, 提香, 罗曼式]
tagline: 探寻提香在维罗纳的唯一真迹《圣母升天》
---
= 维罗纳大教堂 (Duomo di Verona) 深度指南
:page-liquid: true
:toc: macro
:toclevels: 2
:sectnums:
:imagesdir: https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/

这篇指南是维罗纳大教堂 (https://duomodiverona.mymuseum.it/en[Duomo di Verona]) 的深度游览攻略。带领您深入建筑群，欣赏提香在维罗纳的唯一真迹《圣母升天》，圣约翰洗礼堂的红大理石洗礼盆，圣海伦娜教堂的古罗马遗迹，中世纪的门廊，以及更多值得品味的看点。

toc::[]

[#visit]
== 参观信息

维罗纳大教堂坐落在老城区北部的阿迪杰 (Adige) 河畔，距离著名的**石桥** (Ponte Pietra) 只有几步之遥。如今的维罗纳大教堂作为维罗纳大教堂建筑群 (Complesso del Duomo di Verona) 的核心建筑对外开放。这个建筑群包括：

* 维罗纳大教堂 (Duomo di Verona)
* 圣约翰洗礼堂 (Battistero di San Giovanni in Fonte)
* 圣海伦娜教堂 (Chiesa di Sant'Elena)
* 牧师会图书馆 (Biblioteca Capitolare)
* 教士回廊 (Chiostro dei Canonici)

其中，维罗纳大教堂和另外两座附属的小教堂作为一个整体，需要购票参观，票价 4 欧元倒是不贵。推荐购买 link:{% post_url 2026-06-17-verona-card %}[维罗纳卡] (Verona Card)，主要景点全包含。也可以购买四教堂联票，包括维罗纳大教堂建筑群和其它三座维罗纳的主要教堂，票价 8 欧元算是十分良心的了。

牧师会图书馆，也译作**卡皮图拉雷**图书馆，是**欧洲最古老的还在开放的图书馆**，参观需要单独购票，票价 7 欧元不便宜，而且维罗纳卡不能免票，只能享受 1 欧元优惠而已。

从大教堂正门左侧的拱门进去，就可以前往教士回廊。这里不仅通往教堂和图书馆，也通往办公区和教士们的生活区，属于公共通道和连廊，所以可以**免费进入**。

我们来到维罗纳大教堂的主要目标是提香的《圣母升天》祭坛画，只游览了建筑群的三座教堂。这里就聚焦这三座教堂中的看点。

[#battistero-san-giovanni-fonte]
== 圣约翰洗礼堂

圣约翰洗礼堂，意大利语音译叫圣乔瓦尼洗礼堂，是大教堂附属的、专门用来举行洗礼仪式的小教堂，罗曼式建筑，建于 1123 年。

维罗纳大教堂的正门是不开放的。我们去的时候是从大教堂背后的洗礼堂小门检票进入洗礼堂开始游览建筑群的。洗礼堂门楣上方有一块巨大的拱形青铜浮雕，描绘了**施洗者圣约翰**手持贝壳在荒野中的形象，夜空中的鸽子象征着圣灵。

.圣约翰洗礼堂 (Battistero di San Giovanni in Fonte) 的小门是参观维罗纳大教堂建筑群 (Complesso del Duomo di Verona) 的入口。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-entrance-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-entrance-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-entrance-4x3-2400.avif 2400w"]

圣约翰洗礼堂最核心的看点，就是位于教堂中央的洗礼盆。八角形的洗礼盆外层由一整块巨大的维罗纳红大理石镂空雕刻而成；内层还有一个四瓣花形状的小盆。在中世纪时，受洗的信徒站在中央的小盆中，全身浸入水中；神父则站在两层之间的空隙中主持洗礼仪式。

洗礼盆的外壁由中世纪维罗纳著名雕刻和建筑家**布里奥洛托** (Brioloto) 和他的作坊在 1220 年前后雕刻。共有八幅连续的叙事浮雕，刻画了基督降生到受洗的重大事件：天使报喜，圣母访亲与基督降生，天使向牧羊人报喜，三王来朝，希律王下令屠杀无辜婴儿，无辜婴儿的屠杀，逃亡埃及，基督受洗。其中进门后面对的第一面浮雕就是基督受洗。

**布里奥洛托的命运之轮：** 布里奥洛托 (Brioloto de Balneo) 后来因为建造维罗纳**圣泽诺大教堂** (Basilica di San Zeno Maggiore) 被称为“命运之轮”的玫瑰花窗而一举成名。

.维罗纳大教堂 (Duomo di Verona) 的圣约翰洗礼堂 (Battistero di San Giovanni in Fonte)。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-baptismal-font-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-baptismal-font-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-baptismal-font-4x3-2400.avif 2400w"]

除了洗礼盆，洗礼堂的墙壁上有一些遗存的 13-14 世纪壁画残片，还有一幅 16 世纪当地画家**保罗·法里纳蒂** (Paolo Farinati) 创作的油画《基督受洗》。祭坛上的耶稣受难十字架是 15 世纪早期当地艺术家**乔瓦尼·巴迪莱** (Giovanni Badile) 的作品。 

[#chiesa-di-sant-elena]
== 圣海伦娜教堂

我们在大教堂建筑群游览的第二站是洗礼堂隔壁的圣海伦娜教堂。这座教堂的历史可以追溯到公元 9 世纪，建在一座 4 世纪的教堂遗迹之上。而那座教堂由维罗纳的主保圣人**圣泽诺** (San Zeno) 主教建于 4 世纪，是维罗纳最古老的早期基督教教堂。

.维罗纳大教堂 (Duomo di Verona) 建筑群中的圣海伦娜教堂 (Chiesa di Sant'Elena)。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-sant-elena-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-sant-elena-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-sant-elena-4x3-2400.avif 2400w"]

[#duomo]
== 大教堂主殿

大教堂主殿是我们参观的第三站。维罗纳大教堂是维罗纳的主教座堂，正式名称是**母堂圣母主教座堂** (Cattedrale di Santa Maria Matricolare)。

这座教堂是一座完美融合了罗曼式、哥特式与文艺复兴风格的杰出建筑。它始建于 1120 年，最初是一座平顶的罗曼式巴西利卡 (Basilica) 建筑，内部的空间由八个巨大的维罗纳红大理石立柱支撑。在 1440 年，维罗纳的工匠们将红大理石立柱向上延伸，硬生生地加盖出了高耸的哥特式拱顶。到了文艺复兴时期，威尼斯共和国最顶级的建筑大师**米歇尔·圣米凯利** (Michele Sanmicheli) 又为后殿穹顶和主祭坛前设计了弧形大理石祭坛围栏。

.维罗纳大教堂 (Duomo di Verona) 的主殿。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-interior-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-interior-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-interior-4x3-2400.avif 2400w"]

[#titian]
=== 提香的《圣母升天》

维罗纳大教堂主殿中最核心的看点是提香的《圣母升天》。提香 (Titian) 是文艺复兴大师和威尼斯画派泰斗。维罗纳大教堂中的《圣母升天》 (Assunzione della Vergine) 在主殿左侧靠近大门的一个礼拜堂 (Cappella Cartolari-Nichesola) 中，创作于约 1535 年。虽然提香在威尼斯圣方济会荣耀圣母圣殿中的《圣母升天》名气更大，但是维罗纳大教堂中的这幅《圣母升天》是提香留在维罗纳的唯一真迹，也非常值得一看。

.提香 (Titian) 的《圣母升天》在维罗纳大教堂主殿的一个礼拜堂 (Cappella Cartolari-Nichesola) 中。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-cappella-cartolari-nichesola-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-cappella-cartolari-nichesola-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-cappella-cartolari-nichesola-4x3-2400.avif 2400w"]

画面上方是圣母在一群小天使面庞的簇拥下坐在云端；下方是围绕在空石棺周围的使徒们。

**怀疑的托马斯：**画面正中央那位抬头望向天空，伸出一只手臂的使徒就是圣经故事中著名的“怀疑者”托马斯。在耶稣复活时，十二使徒之一的托马斯没有亲眼所见，非要把手指伸入耶稣手掌上被钉和肋骨旁被刺的伤口才信。当圣母升天时，托马斯再次错过了，所以当其他使徒把他带到空棺前，他也坚决不信。已经升天的圣母了解托马斯的秉性，于是显现在云端，将自己的腰带抛到了托马斯的手里。托马斯终于相信了神迹。如今，传说中的“圣母腰带”就供奉在维罗纳附近的小城**普拉托** (Prato) 的主教座堂中。

.维罗纳大教堂 (Duomo di Verona) 中的《圣母升天》是提香 (Titian) 留在维罗纳的唯一真迹。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-assumption-titian-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-assumption-titian-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-assumption-titian-4x3-2400.avif 2400w"]

[#falconetto]
=== 法尔科内托的幻觉透视壁画

在提香的《圣母升天》正对面，是大教堂正殿中极为吸睛的两座礼拜堂，墙壁上布满了由文艺复兴早期大师**乔瓦尼·玛丽亚·法尔科内托** (Giovanni Maria Falconetto) 于 1503 年绘制的幻觉透视壁画。

.维罗纳大教堂 (Duomo di Verona) 中乔瓦尼·玛丽亚·法尔科内托 (Giovanni Maria Falconetto) 绘制的幻觉透视壁画。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-giovanni-maria-falconetto-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-giovanni-maria-falconetto-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-giovanni-maria-falconetto-4x3-2400.avif 2400w"]

如果你时间充裕，在大教堂的后殿穹顶和主祭坛这一侧，有另外几处看点。

[#apse]
=== 后殿穹顶

后殿穹顶上布满了壁画，中心的主题依然是《圣母升天》；而环绕它的小画描绘的是《圣母诞生》、《圣母加冕》，和《献耶稣于圣殿》。值得一提的是，穹顶远看宏大而绚丽，极具视觉冲击力。可是近看，会发现画中的人物有些粗糙和笨拙。这是因为整套壁画的设计是由文艺复兴后期最杰出的大师之一**朱利奥·罗马诺**(Giulio Romano) 完成的。罗马诺是文艺复兴三杰之一的**拉斐尔**最得意的徒弟和继承人。作为拉斐尔去世后，全意大利最负盛名的画家之一，他没有时间去完成穹顶的绘制。绘制工作实际上是由维罗纳当地的画家**弗朗切斯科·托尔比多** (Francesco Torbido) 完成的。

.维罗纳大教堂 (Duomo di Verona) 的后殿穹顶。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-apse-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-apse-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-apse-4x3-2400.avif 2400w"]

[#predella-di-michele-da-verona]
=== 米歇尔的祭坛底座画

在主祭坛大理石围栏左侧的祭坛是马费伊祭坛 (Altare Maffei)。这里原有的祭坛画是由文艺复兴时期维罗纳画家**米歇尔·达·维罗纳** (Michele da Verona) 创作的。如今，原有的祭坛主画被后世的一幅画替换下来并藏于维罗纳大教堂博物馆（没有对公众常规开放），但是祭坛底座上的装饰画是米歇尔的原作。大教堂还特为刚刚修复过的这幅底座装饰画制作了介绍展板。

在狭小的底座空间上，画家将圣母玛利亚父母，乔阿基诺 (Gioacchino) 和安妮 (Anna) 的四个重要场景描绘在其中。从左到右分别是：因为“不育”，乔阿基诺被祭司拒绝进入耶路撒冷圣殿献祭；乔阿基诺在山林中祈祷，直到天使宣告他们即将生育的喜讯；乔阿基诺赶回家中和迎接他的安妮拥抱；圣母玛利亚的诞生。

.维罗纳大教堂 (Duomo di Verona) 中的米歇尔·达·维罗纳的祭坛底座画 (Predella di Michele da Verona)。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-predella-michele-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-predella-michele-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-predella-michele-4x3-2400.avif 2400w"]

[#arca-di-sant-agata]
=== 圣阿加莎石棺

在主祭坛大理石围栏右侧的礼拜堂是**马赞蒂**礼拜堂 (Cappella Mazzanti)，由大教堂的修士**弗朗切斯科·马赞蒂** (Francesco Mazzanti) 于 1508 年出资翻建，主要供奉的是圣方济各和圣阿加莎。没错，就是那个有名的马赞蒂家族。香草广场 (Piazza Erbe) 那一排画满壁画的建筑正是**马赞蒂之家** (Case dei Mazzanti)。

++++
{% related slugs="verona-piazza-erbe" %}
++++

马赞蒂礼拜堂里摆放着一座中世纪哥特式大理石雕刻艺术的杰作，**圣阿加莎**石棺 (Arca di Sant'Agata)。这座石棺最著名的部分是锥形的华盖顶端，用雕塑刻画了圣阿加莎殉道的震撼一幕：由于她拒绝了古罗马总督的追求并坚守基督教信仰，总督下令对她施以酷刑。圣阿加莎双臂张开，两名刽子手正拿着巨大的剪钳，残忍地割掉她的乳房。

.维罗纳大教堂 (Duomo di Verona) 中的圣阿加莎石棺 (Arca di Sant'Agata)。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-arca-di-sant-agata-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-arca-di-sant-agata-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-arca-di-sant-agata-4x3-2400.avif 2400w"]

正因为殉道的惨烈，圣阿加莎成为乳腺疾病的主保圣人。意外的是，她同时也因为中世纪的误会成了面包师的守护神。

**坎皮奥内大师：**圣阿加莎石棺由某位没有留下姓名的**坎皮奥内大师** (Maestri Campionesi) 建造于 1353 年。同样作为坎皮奥内大师一员，也是其代表人物的**博尼诺·达·坎皮奥内** (Bonino da Campione) 建造了著名的**斯卡利杰罗**领主墓 (Arche Scaligere) 中最繁复的**坎西尼奥里奥** (Cansignorio) 之墓。

尽管这件艺术品被称为“圣阿加莎石棺”，但是圣阿加莎的遗骨在她的家乡西西里岛。维罗纳的石棺中安放的其实是 8 世纪时维罗纳一位主教姐姐的遗骨。

[#exterior]
== 大教堂门廊

走出维罗纳大教堂，不要急着离开。这里的门廊是中世纪北意大利罗曼式雕刻宗师**尼科洛** (Niccolò) 的巅峰之作，中世纪建筑的典范。

门廊指的是教堂外立面向外突出、像亭子一样的入口建筑结构。门廊不但可以为人遮风挡雨，还可以保护大门上的雕刻，是罗曼式建筑中具有代表性的特征。维罗纳大教堂的门廊是双层的，体量更为宏大，是这一结构的杰出范例。

.维罗纳大教堂 (Duomo di Verona) 的外立面。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-facade-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-facade-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-facade-4x3-2400.avif 2400w"]

整个门廊以及门楣的雕塑非常复杂，充满了中世纪宗教和世俗的形象符号。

* 在门廊的基座上，两只**狮鹫**有着鹰嘴和紧贴身体的翅膀，驮着支撑门廊的支柱，都是由维罗纳红大理石雕刻而成。
* 大门两侧的立柱上排列着十位圣经先知的浮雕，上面的铭文说明了他们的身份。
* 立柱最外侧正面雕刻的两尊人像刻画的是查理曼大帝麾下十二圣骑士的核心人物。左侧是圣骑士之首**罗兰** (Roland)，手持**杜兰德尔**圣剑，剑身上刻着圣剑的名字。他是扑克牌中方块 J 的原型。右侧人物则是奥利维 (Oliver)。
* 门楣上雕刻的是神学三美德的化身：信、望、爱。
* 门楣上半圆形的浮雕刻画的是向牧羊人报喜，宝座上的圣母和圣婴，和三王来朝。
* 拱顶内侧雕刻着四位福音书作者的象征：狮、牛、人、鹰。
* 拱顶右侧是施洗者圣约翰，伸手指向拱顶中央带着十字架的羔羊。手指上边的铭文写道：上帝的羔羊在此 (Ecce Agnus Dei)。

.维罗纳大教堂 (Duomo di Verona) 的门廊。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-protiro-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-protiro-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-protiro-4x3-2400.avif 2400w"]

建造这座门廊的雕塑家尼科洛虽然不及文艺复兴时期的雕塑大师有名，但他在 12 世纪上半叶是罗曼式建筑雕塑的宗师，在艺术史上具有不可替代的地位。他还建造了维罗纳圣泽诺大教堂的门廊。作为最早自我觉醒的极少数中世纪艺术家之一，他在两处门廊都留下了“自吹自擂”的拉丁文签名诗句。其中维罗纳大教堂的签名诗句刻在紧贴底层门廊上沿，拱顶中央“上帝的羔羊”浮雕之上的狭长条带上。大意是：“这位雕刻了这些作品、技艺精湛的工匠尼科洛，人们世代传颂他”。其中拉丁语形式的尼科洛名字 (NICOLAVM) 正好在羔羊的左上方。

.维罗纳大教堂 (Duomo di Verona) 的门廊上尼科洛的 (Niccolò) 签名诗句。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-portal-nicolo-signature-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-portal-nicolo-signature-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-portal-nicolo-signature-4x3-2400.avif 2400w"]

[#blue-angel]
== 蓝天使

在大教堂门前小广场上，一尊天使雕像格外引人注目。他手臂张开，象征欢迎和接纳。这是由维罗纳当地艺术家创作于 2015 年的一件现代装置艺术品。人们常叫它《蓝天使》。

[#campanile]
== 钟塔

维罗纳大教堂的钟塔是维罗纳第二高的建筑，仅次于香草广场旁的**朗贝尔蒂塔** (Torre dei Lamberti)。

这座钟塔还是历经中世纪、文艺复兴时期和近代建设，仍然未能完工的建筑。其中一层和二层是建于 12-13 世纪的巨大罗曼式基座。到了文艺复兴时期，由前文提到的著名建筑师米歇尔·圣米凯利主持设计，保留基座，重建钟塔。可惜刚刚加了一层塔身到教堂的高度，就因资金问题停工，一停就是 300 多年。到了 20 世纪初，维罗纳重启建设，加高了塔身，完成了塔顶的钟铃房。可惜再次遇到资金问题，原计划的尖顶搁置了。本来可以一举成为维罗纳第一高塔的，现在只能屈居第二，维持今天所见的平顶样子了。

尽管如此，大教堂的钟楼仍然是维罗纳天际线最具辨识度的建筑。从阿迪杰河对岸的圣彼得城堡 (Castel San Pietro) 望向石桥 (Ponte Pietra)，大教堂和钟塔是绝美的背景。

.从圣彼得城堡 (Castel San Pietro) 望向石桥 (Ponte Pietra)，维罗纳大教堂 (Duomo di Verona) 和它的钟塔是绝美的背景。
image::https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-campanile-ponta-pietra-4x3-1200.avif[srcset="https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-campanile-ponta-pietra-4x3-1200.avif 1200w, https://assets.lilyroger.com/images/trips/2026/dolomites/verona-duomo/duomo-verona-campanile-ponta-pietra-4x3-2400.avif 2400w"]

