= 法罗群岛攻略
:page-categories: posts
:page-date: 2025-06-28 08:00:00 +0100
:page-modified_time: 2025-06-28 08:00:00 +0100
:page-layout: post
:page-subtitle: Guide to Faroe Islands
:page-tags: [2025-Lofoten-Faroe, 欧洲, 北欧, 斯堪的纳维亚, 丹麦, 法罗群岛]
:page-liquid:
:toc:
:sectnums:

法罗群岛看什么, 做什么, 去哪里, 住哪里?

== 基本信息

参考: https://visitfaroeislands.com/en/about-vfi/history-governance-and-economy/quick-facts[Quick Facts]

== 法罗群岛什么时候去最好

=== 法罗群岛年度闭岛维护

闭岛维护 (https://visitfaroeislands.com/en/closedformaintenance[Closed For Maintenance]) 是法罗群岛有一项非常特别且有远见的可持续旅游发展倡议. 从 2019 年开始, 法罗群岛每年择期对游客关闭大部分的景点两三天, 基本上就是 "闭岛". 在这几天里, 来自全世界的上百名志愿者会同当地的志愿者一起对法罗群岛的景点加以维护.

前往法罗群岛之前, 一定要留意当年的闭岛时间. 最近的年度闭岛日是 2025 年 5 月 的 1 - 3 日.

== 法罗群岛的交通

唯一机场沃格机场 (Vágar Airport) 进出.

首都托尔斯港 (Tórshavn) 可以乘坐机场大巴到达.

从 Tórshavn 经隧道系统可以在一小时内到达群岛有公路连接的任意角落.

所有的轮渡和公交车都支持信用卡.

四条收费https://www.tunnil.fo/english/[海底隧道]将几个主要的大岛连接在一起.

== 法罗群岛住在哪

首都托尔斯港拥有最多的住宿选项. 很多旅行团也是从这里出发. 海底隧道系统四通八达. 所以, 托尔斯港是最佳的基地选项. 机场所在的沃格岛也可以作为游览沃格岛和前往米基内斯观鸟的基地. 而北方的克拉克斯维克镇则是探索北方诸岛的最佳基地.

== 法罗群岛区域指南

下面是法罗群岛的各个区域的重要信息:

沃格 (Vágar):: 西岛, 机场, 瀑布, 悬湖, 前往米基内斯岛观海鹦的轮渡

米基内斯 (Mykines):: 西部, 轮渡, 海鹦, 大小海蚀柱

斯特莱默 (Streymoy):: 中部, 洋流之岛, 首都托尔斯港, 萨克松和特约尔努维克村落

伊斯特罗伊 (Eysturoy):: 东岛, 巨人和女巫海蚀柱, 海蚀峡谷, 海岸足球场

北方诸岛 (Norðoyar, Northern Islands):: 六个北部小岛, 卡卢林灯塔, 邦德墓碑, 海豹女雕像, 克拉克斯维克镇

桑多伊岛 (Sandoy Island):: 沙岛, 南部, 海底隧道, 利拉伯格悬崖, 前往斯库沃伊岛观鸟的码头

苏杜罗伊岛 (Suðuroy Island):: 南岛, 轮渡

== 沃格岛

沃格岛在法罗群岛的西部, 是法罗群岛的第三大岛. 沃格岛是法罗群岛唯一机场的所在地, 通过海底隧道可以前往位于斯特莱默岛的首都托尔斯港, 乘轮渡可以前往米基内斯岛去观鸟.

沃格岛从机场出发自东向西沿着海岸线有三个村子:

* 瑟沃格 (Sørvágur)
* 布尔 (Bøur)
* 加萨达鲁尔 (Gásadalur)

瑟沃格村子东边就是机场, 西边就是前往米基内斯岛的轮渡码头. 从瑟沃格村沿着海岸往西就是布尔村. 这里有错落的草皮屋顶的老房子, 以远处的廷霍尔穆尔岛 (Tindhólmur) 和米基内斯岛做背景. 继续向西前行 5 公里, 在巍峨的群山之下的小村子就是加萨达鲁尔村 (Gásadalur). 那里有穆拉瀑布 (Múlafossur).

在沃格岛的东端有著名的瑟沃格湖 (Sørvágsvatn), 也被称为 "悬湖" (Leitisvatn). 瑟沃格湖是法罗群岛最大的湖泊. 徒步 (需付费) 可以到达湖南端的观景点, 从这个视角看过去, 湖仿佛漂浮在海面之上. 更多的信息可以参考:

* https://visitfaroeislands.com/fo/whatson/places/place/lake-sorvagsvatn-leitisvatn[Lake Sørvágsvatn/Leitisvatn]

特罗尔科努芬古尔 (Trøllkonufingur) 的意思是 "女巨魔的手指", 是沃格岛海岸上的一座高耸的奇石. 如何徒步前往这块奇石的观景点, 可以参考:

* https://guidetofaroeislands.fo/travel-faroe-islands/drive/troellkonufingur/[Trøllkonufingur Rock Pillar Travel Guide]

== 米基内斯岛

米基内斯岛法罗群岛最西端的岛. 岛上唯一的村子也叫米基内斯. 在夏季, 可以从沃格岛的瑟沃格村搭乘轮渡米基内斯岛. 这里是最热门的观赏海鹦的地方.

米基内斯岛上观鸟必须跟随官方的导游团队, 并支付所谓的徒步费 (Hiking Fee). 每天两个团, 上午和下午各一个团, 时间是配合公共交通的轮渡时间的. 可以在 https://hiking.fo/lysing/redirect/31[hiking.fo] 在线预定并缴费, 也可以在岛上直接缴费. 提前至少一天预定每名成人需要 400 丹麦克朗徒步费 + 少许杂费. 在岛上现场缴费更贵, 是 500 丹麦克朗.

https://guidetofaroeislands.fo/book-holiday-trips/mykines-ferry/

== 斯特莱默岛

斯特莱默岛 (Streymoy) 意为 "洋流之岛", 因环绕该岛的强大潮汐洋流而得名. 它是法罗群岛中最大, 人口最多的岛屿. 该岛名源于法罗语中的 "streymur" (意为 "洋流") 和 "oy" (意为 "岛屿"). 首府托尔斯港就在这座岛上. 整个岛从上到下绵延约 50 公里.

在斯特莱默岛的最北端, 是两个最偏僻同时也是最美的小村子:

* 特约尔努维克 (Tjørnuvík)
* 萨克松 (Saksun)

特约尔努维克村在道路的尽头, 座落在冰河时代形成的完美圆形冰川谷中, 三面环山, 一面是沙滩. 前往特约尔努维克村的路上会经过法罗群岛最高的瀑布:

* 福萨瀑布 (Fossá)

附近的萨克松村是法罗群岛另一个最美村庄之一. 这里, 一排排草皮屋顶的房屋, 沿着达拉河（Dalá）绵延而立, 俯瞰着一座白色的石砌教堂和一个泻湖.

前往特约尔努维克和萨克松村的两段路都是法罗群岛的旅游公路路线的一部分. 这些旅游公路路线以法罗群岛的国花金凤花 (学名毛茛) 命名, 称为 https://www.landsverk.fo/en-gb/weather-and-driving-conditions/tourist-routes-in-the-faroe-islands[Sóljuleiðir (Buttercup Routes)].

== 伊斯特罗伊

伊斯特罗伊岛是法罗群岛的第二大岛, 因为大体上位于斯特莱默岛东北方向, 最早来到这个岛上定居的维京人将其命名为伊斯特罗伊 (Eysturoy), 直译就是 "东岛" 的意思. 东岛是一个独立的岛, 但现在一条新的海底隧道将其与邻近的斯特莱默岛连接起来, 前往托尔斯港的车程现在只需 20 分钟. 此外, 还有一座桥连接着东岛和斯特莱默岛, 虽然不如海底隧道便捷, 但可以省去海底隧道费用.

在伊斯特罗伊岛的北端有几个热门的去处:

* 巨人和女巫 (Risin & Kellingin) 海蚀柱
* 格约格夫 (Gjógv) 海蚀峡谷
* 艾迪 (Eiði) 的海岸足球场 (现在用作露营车营地)

== 北方诸岛

北方诸岛包括在法罗群岛北部的六个小岛:

* 富格洛伊岛 (Fugloy)
* 斯维诺伊岛 (Svínoy)
* 维多伊岛 (Viðoy)
* 博多伊岛 (Borðoy)
* 库诺伊岛 (Kunoy)
* 卡尔索伊岛 (Kalsoy)

在北方诸岛上, 最值得一去的地方包括:

* 克拉克斯维克镇 (Klaksvík)
* 米克拉达鲁尔村 (Mikladalur)
* 特罗拉内斯村 (Trøllanes)

克拉克斯维克镇是法罗群岛第二大城镇, 坐落在陡峭的群山之间, 是一个迷人的渔业中心. 这里北方诸岛的门户. 事实上, 如果你有足够的时间在法罗群岛呆在一段时间, 克拉克斯维克是探索北方诸岛的理想基地, 拥有便利的住宿, 咖啡馆和餐厅选择. 克拉克斯维克也是这片岛屿所有交通的枢纽, 公交车, 公路以及北部两条渡轮路线之一都从这里辐射出去.

米克拉达鲁尔村是卡尔索伊岛岛四个村子中最大的一个. 除了漂亮的草皮房顶的房子之外, 传说中的海豹女 (The Seal Woman, Kópakonan) 的雕像就树立在海边.

特罗拉内斯村是卡尔索伊岛岛最北端的村子. 这里的卡卢林灯塔 (Kallurin) 已经成为游客最喜爱的景点之一. 从特罗拉内斯村到卡卢林灯塔的徒步路线 (需要徒步费) 是法罗群岛最热门徒步路线. 有趣的是, 在徒步的尽头附近, 詹姆斯·邦德的墓碑竖立在山崖边, 纪念在 "无暇赴死" 中死在这个山谷里的邦德. 完成卡卢林灯塔徒步可不太容易, 具体的信息可以参考:

* 卡卢林一日游 (周一, 三, 五): https://vfibackend.com/uploads/55388-vfi-rutukort-a4-kallurin.pdf[Day trip to Kallurin]

== 沙岛

沙岛在斯特莱默岛的南边, 有海底隧道连接着两个岛.

从沙岛的斯科蓬村 (Skopun) 可以徒步到利拉伯格悬崖 (Líraberg Cliff), 沿途欣赏到雄伟的山崖, 丰富的鸟类, 和海蚀柱.

沙岛还是前往著名的斯库沃伊岛 (Skúvoy) 的门户. 在沙岛南岸的桑杜尔村 (Sandur) 的码头, 每天有几班轮渡往返于沙岛和斯库沃伊岛之间. 斯库沃伊岛有鸟类自然保护区. 如果没能在米基内斯岛看到海鹦, 可以在这里看看. 维京酋长西格蒙杜尔·布雷斯蒂松 (Sigmundur Brestisson) 就埋葬于此.

== 苏杜罗伊岛

苏杜罗伊岛名字的意思是 "南岛". 从托尔斯港乘坐轮渡两个小时左右可以到达. 因为这次法罗群岛的行程时间有限, 而南岛太远, 所以, 我们放弃南岛.

== 参考资料

* https://visitfaroeislands.com/en[法罗群岛官方旅游推广机构]
* https://visitfaroeislands.com/en/closedformaintenance[法罗群岛官方旅游推广机构 - 闭岛维护]
* https://visitfaroeislands.com/en/plan-your-stay/need-a-little-help/regional-information-centres[法罗群岛官方旅游推广机构 - 区域信息中心]
