---
layout: article
categories: posts
date: 2026-06-15 08:00:00 +0100
tags: [2026-Dolomites, 欧洲, 南欧, 意大利, 多洛米蒂]
tagline: 拉定尼亚，木雕，侏儒国王劳林和玫瑰花园山的传说。
---
= 拉定尼亚 (Ladinia): 多洛米蒂 (Dolomites) 的古老文化之魂
:page-liquid: true
:toc: macro
:toclevels: 2
:sectnums:
:imagesdir: https://assets.lilyroger.com/images/trips/2026/dolomites/ladinia

在多洛米蒂，你经常会发现路牌上除了意大利语和德语，还有第三种语言，这就是**拉定语** (Ladin, 发音: [luh-**deen**])。拉定语是该地区除意大利语和德语之外的第三种官方语言，也是多洛米蒂真正的文化灵魂。

toc::[]

[[ladin]]
== 拉定 (Ladin)

拉定人 (Ladins) 是分布于意大利北部的一个民族。

公元前 15 cite:[wrcra] 年罗马人征服阿尔卑斯山后, 当地的原住民雷蒂亚人 (Rhaeti) 被迫开始学习罗马士兵的“通俗拉丁语”。这种语言在封闭的山谷中演化了两千年，才形成了今天的拉定语 (Ladin)。而今天的拉定人正是雷蒂亚原住民与古罗马士兵的后裔。

在南蒂罗尔省（博尔扎诺省），拉定语是与德语、意大利语平等的第三官方语言。

[[ladinia]]
== 拉定尼亚 (Ladinia)

拉定语目前主要保留在多洛米蒂核心区环绕**塞拉群峰** (Sella group) 的五个山谷中，这些山谷统称为**拉定尼亚**：

* 加尔代纳山谷 (Val Gardena): 奥蒂塞伊的所在地，木雕艺术的发源地。
* 巴迪亚山谷 (Val Badia): 以保存完好的古老民居群 (Viles) 著称。
* 法萨山谷 (Val di Fassa): 位于特伦托省，充满传说色彩的玫瑰花园山 (德语: Rosengarten; 意大利语: Catinaccio) 所在地。
* 利维纳隆戈山谷 (Livinallongo): 位于贝卢诺省，波尔多伊山口脚下。
* 安佩佐山谷 (Ampezzo): 即东部核心区科尔蒂纳丹佩佐周边。

[[culture-icons]]
== 拉定元素

在多洛米蒂，你会在很多地方感受到拉定文化。如果时间充裕，还可以参观位于巴迪亚山谷的**拉定博物馆** (Museum Ladin)，那里能系统地了解这个民族的历史。

[[language]]
=== 三语地名

在奥蒂塞伊等地，你会看到路牌上有三种语言。比如奥蒂塞伊地名对应的 Ortisei / St. Ulrich / Urtijëi 分别是意大利语，德语，最后那个 Urtijëi 就是拉定语。

[[blue-white-green]]
=== 拉定三色旗

在很多山屋和节庆场合，你会看到拉定的蓝、白、绿三色旗。蓝色代表天空，白色代表积雪，绿色代表草甸。

[[woodcarving]]
=== 拉定木雕

拉定木雕是拉定文化的名片之一，加尔代纳山谷的奥蒂塞伊更是世界木雕之都，随处可见精美的圣像和现代木雕作品。

拉定木雕的历史可以追溯到 17 世纪初，当时，奥蒂塞伊周边极其贫穷，冬季大雪封山长达数月。农民们为了打发时间并赚取额外收入，开始利用当地盛产的瑞士石松 (Swiss Pine) 制作简单的农具和宗教雕像。到了 18 世纪，加尔代纳的木雕圣像（耶稣像、圣母像）开始通过走街串巷的商人传遍整个欧洲的教堂。在 19 世纪，这里生产了数以百万计的木质关节玩偶。虽然被称为“荷兰娃娃” (Dutch Dolls)，但其实几乎全部产自加尔代纳。这些玩偶曾是维多利亚时代欧洲和美国孩子们最渴望的礼物。

为了保护本土手工艺，当地商会推出了 "Prodotto Legno Val Gardena" 认证。只有完全在山谷内手工完成的作品才能贴上这个带有小金属圆牌的标签。

位于奥蒂塞伊市中心。加尔代纳博物馆 (Museum Gherdëina) 收藏了大量 17 世纪以来的古老木雕、关节玩偶以及著名的“拉定木质祭坛”。

[[les-viles]]
=== 拉定人农舍群落 (Les Viles)

拉定语 Les Viles 是 Vila 的复数形式，指的是拉定人将住宅与牲畜棚紧密相连的农舍群落。

与南蒂罗尔典型的独立农庄不同，在巴迪亚山谷的坡地上，几户拉定人家（通常是亲属关系）会将农舍、谷仓、马厩紧密地建造在一起，并共享中间的烤炉、粮仓、谷物烘干房、木柴房、水槽以及连接各处的村落小广场，形成一个农舍群落，即拉定语中的 Vila。

这种居住模式体现了拉定人几千年来“集体生存”的哲学 - 共享资源、共同抵御雪灾和野兽。这种 Vila 不但最大限度地留出宝贵的耕地和牧场，不让建筑蚕食农田；每个 Vila 往往就是一个大家族，这种紧密结构又使得拉定语和传统习俗得以很好的世代相传下来。

如果你对拉定人的农舍群落有兴趣，而且时间充裕的话，不要错过位于博尔扎诺省圣马蒂诺-因巴迪亚 (San Martino in Badia) 自治市的**龙贾鲁** (Longiarù) 村，从博尔扎诺出发约需 1.5 小时车程。从龙贾鲁村沿着小溪 (Rio Seres) 旁的步道向上，小溪两边分别是 Miscì 和 Seres 两个非常有名的拉定农舍群落。步道继续向上则是在拉定语中称为 Val di Morins 的水车谷 (The Mill Valley)。这里有一连串八座被精心复原的古老水车，它们曾经服务于这些农舍群落，用于磨制谷物。

[[enrosadira]]
=== 日照金山 (Enrosadira)

多洛米蒂山脉在日出或日落时分，由于白云石独特的矿物成分碳酸钙和碳酸镁反射阳光，山体会呈现出从金黄、橘红到粉紫等鲜艳色彩。这种“日照金山”奇观在多洛米蒂地区有个独有的名字 Enrosadira。这个单词源自拉定语单词 enrosadöra 一词，字面意思就是“变成粉红色”。

在多洛米蒂的日照金山背后，还有拉定人口口相传的“玫瑰花园山” (德语: Rosengarten; 意大利语: Catinaccio) 神话：

相传在远古时代，侏儒国王劳林 (King Laurin) 在多洛米蒂的山岩之间拥有一座巨大的玫瑰花园。劳林爱上了邻国的公主希尔德 (Similde) 并将其劫持。为了营救公主，伯尔尼的狄特里希 (Dietrich von Bern) 率领骑士攻入花园。

劳林披上隐身斗篷躲在玫瑰丛中，但由于他踩踏玫瑰发出的沙沙声和折断的枝条露出了破绽，最终被骑士抓获。

愤怒的劳林认为是这片美丽的玫瑰花园背叛了他。于是他下达诅咒：“无论是白天还是黑夜，谁也别想再看见这些玫瑰！”

劳林在下诅咒时忘记了黎明和黄昏。于是，在这两个时刻诅咒失效，凋零的玫瑰重新焕发红光，将山峰染成梦幻的粉红色。

=== 拉定美食

拉定菜系混合了山地农家风味。推荐尝试 Cajincì（一种填充菠菜和凝乳的油炸或水煮饺子）。

[bibliography]
[#resources]
== 参考资料

bibliography::[]