---
layout: article
categories: posts
date: 2026-02-10 12:00:00 +0100
tags: [2026-Alps-Lofoten, 欧洲, 西欧. 法国, 里昂]
tagline: 曾经的高卢人之都和如今的法国美食之都
liquid: true
---
= 里昂 (Lyon) 指南 - 初访者的城市攻略
:toc:
:toclevels: 1
:sectnums:

探索曾经的高卢人之都和如今的法国美食之都里昂，这份攻略专为初访者设计。深入世界遗产里昂老城、探秘 Traboules 秘密通道，品尝地道 bouchons 美食。本指南提供快速游览里昂的实用信息、必看景点（如富维耶圣母院和金头公园）和交通攻略。

里昂 (Lyon) 位于法国东南部，是奥弗涅-罗讷-阿尔卑斯大区的首府，被公认为法国的“第二大都市区”。它坐落在罗讷河（Rhône）与索恩河（Saône）的交汇处，拥有超过2000年的悠久历史。

== 里昂的街区

法国里昂（Lyon）市中心共划分为 9个市政区（Arrondissements），每个区都有其独特的历史背景和生活氛围： 

* 第1区 (1er)：位于市中心北侧，包含著名的 泰罗广场 (Place des Terreaux) 和市政厅。这里是文化与艺术的聚集地，拥有众多极具个性的酒吧和咖啡馆。
* 第2区 (2e)：坐落在半岛区（Presqu'île）的南部，是里昂最繁华的商业中心。包含 白莱果广场 (Place Bellecour) 以及近年来新兴的现代化建筑群 汇流区 (Confluence)。
* 第3区 (3e)：人口最多的行政区。里昂的中央商务区 帕尔迪厄 (Part-Dieu) 位于此地，这里也是主要的交通枢纽，设有重要的火车站和大型购物中心。
* 第4区 (4e)：涵盖了 红十字山 (La Croix-Rousse) 高地。这里曾是著名的丝绸纺织中心，如今充满了波西米亚风格和浓厚的社区文化氛围。
* 第5区 (5e)：包括 里昂老城 (Vieux Lyon) 和 富维耶山 (Fourvière)。这里是联合国教科文组织的世界文化遗产区，拥有著名的富维耶圣母院和古罗马剧院遗址。
* 第6区 (6e)：被公认为里昂最优雅、最富有的住宅区。欧洲最大的城市公园之一 金头公园 (Parc de la Tête d'Or) 便坐落于此。
* 第7区 (7e)：面积最大的区，是一个充满活力的多元文化区域。拥有多所大学校舍（如里昂高等师范学院）和新兴的创意街区。
* 第8区 (8e)：现代电影的诞生地，卢米埃尔博物馆 位于此处。该区以住宅和工业遗产改造后的文化空间著称。
* 第9区 (9e)：位于西北部，近年来经历了大规模的城市更新。包含 韦斯 (Vaise) 等区域，是许多科技企业和初创公司的所在地。 
* 此外，从地理上通常将里昂简单分为三大部分：西部的历史古城（5区）、中部的半岛商业区（1、2、4区）以及东部的现代生活区（3、6、7、8、9区）。

== 里昂的核心旅游街区

* 富维耶山 (Fourvière)：俯瞰全城的圣母圣殿所在地，被称为“祈祷之丘”。
* 红十字山 (La Croix-Rousse)：昔日的丝织工聚居地，被称为“劳动之丘”。
* 半岛区 (Presqu'île)：市中心最繁华的商业与文化街区。


交互式地图参考: https://visitlofoten.com/en/topic/places-to-go/[Visit Norway]

[#presquile]
== 半岛区

里昂的半岛区 (Presqu'île) 是指代索恩河 (Saône) 和罗讷河 (Rhône) 之间，从北部的红十字山 (Croix-Rousse) 的南坡一直延伸到两河汇流点的整片半岛。也就是说由行政区划的第 1 区和第 2 区共同组成。

* 第 1 区（北段）： 涵盖了从沃土广场 (Place des Terreaux) 到红十字山南坡 (Les Pentes) 的区域。这里是半岛区的文化和艺术核心。
* 第 2 区（中南段）： 涵盖了从白莱果广场 (Place Bellecour) 向南，经过佩拉什区 (Perrache) 直到汇流区 (La Confluence)。这里是半岛区的商业、交通和行政核心。

其中在第 2 区，是里昂半岛区的核心，从北向南又可以进一步细分为几个区域：

科德利埃 - 白莱果 (Bellecour - Cordeliers) 商业核心区:: 从第 1 区交界处延伸至 白莱果广场 (Place Bellecour)，这里是里昂的“市中心”。白莱果广场是
艾奈区 (Ainay)
佩拉什区 (Perrache)
汇流区 (La Confluence)


Cordeliers（科德利埃区）位于里昂半岛区（Presqu'île）的中心地带，主要属于里昂第 2 区。它是里昂最繁华、历史最悠久的商业和金融中心之一，连接着北部的沃土广场（Terreaux）和南部的白莱果广场（Bellecour）。

== 如何前往里昂

[#train-stations-of-lyon]
=== 里昂的火车站

这里重点介绍里昂最重要的位于市中心的两个主要火车站：

* 里昂帕尔迪厄站 (Gare de Lyon-Part-Dieu)
* 里昂佩拉什站 (Gare de Lyon-Perrache)

里昂帕尔迪厄站位于第 3 区，里昂最核心的交通枢纽，也是全欧洲最繁忙的换乘站之一。绝大多数 TGV 高铁 均在此停靠。如果你从巴黎、马赛、日内瓦、布鲁塞尔，通常会在此下车。

里昂佩拉什站位于第 2 区，处于半岛区的中心位置，是历史悠久的老牌火车站。里昂佩拉什站主要是 TER 省际列车始发或终点站。如果你需要前往周边城镇，或乘坐长途大巴 (FlixBus / BlaBlaCar Bus)，这里是主要枢纽站。

我们从巴黎到里昂选择了乘坐性价比更高的意铁的红箭高铁，在里昂的终点站就是里昂佩拉什站。里昂帕尔迪厄站是经停的前一站。而随后我们前往小城安纳西 (Annecy) 就是在里昂佩拉什站乘坐的长途大巴。


== 里昂的串廊 (Traboules)

里昂的“串廊”是一个里昂特有的文化符号，类似于北京的“胡同”或上海的“弄堂”。串廊是法语 Traboules 的意译，。 是深入这座城市历史灵魂的最佳方式。老城的通道以优雅的庭院和意式长廊著称，是 15-16 世纪繁荣商业的见证。 

很多串廊的大门看起来是关着的，但只要旁边有青铜牌且在开放时间内，你通常可以按下门口的按钮（标注为 "Services" 或 "Traboule"）开门进入。


* 最长串廊 (La Longue Traboule)：入口在 54 Rue Saint-Jean。它横跨三座庭院，直通另一条街，是老城最具代表性的迷宫。
* 粉红塔楼 (La Tour Rose)：位于 22 Rue du Bœuf。虽然它更像是一个庭院，但其标志性的粉色圆形楼梯塔是里昂出镜率最高的地方。
* 蝉之屋 (Maison des Avocats)：位于圣让广场附近，拥有精美的连拱廊，展现了典型的文艺复兴庭院美学。


[#lyon-top-attractions]
== 里昂必看必玩清单 (Top Attractions)

=== 1. 里昂老城 (Vieux Lyon) 与 秘密通道 (Traboules)

* *必玩理由* : 欧洲规模最大的文艺复兴街区之一。
* *核心体验* : 穿梭于建筑内部的 *秘密通道 (Traboules)*，这些走廊曾是丝绸工匠的捷径。
* *打卡点* : https://primatiale.fr/[里昂主教座堂 (Cathédrale Saint-Jean)]

=== 2. 富维耶山 (Fourvière)

* *必玩理由* : 里昂的发源地，全城制高点。
* *核心体验* : 乘坐独特的 *登山缆车 (Funiculaire)* 上山，俯瞰全城红屋顶。
* *打卡点* : https://www.fourviere.org/en/[富维耶圣母圣殿 (Basilique Notre-Dame de Fourvière)] 与 https://lugdunum.metropolelyon.fr[古罗马剧院 (Théâtre antique)]

=== 3. 金头公园 (Parc de la Tête d'Or)

* *必玩理由* : 法国最大的城市公园，内含一个 *免费动物园 (Zoo de Lyon)*。
* *核心体验* : 在湖上划船或在玫瑰园散步。

=== 4. 红十字山 (La Croix-Rousse)

* *必玩理由* : 曾经的丝绸工人之山，现为艺术气息浓郁的 *波西米亚街区 (Bohemian district)*。
* *打卡点* : https://www.lyon-france.com[丝织工墙画 (Mur des Canuts)] — 全欧洲最大的错视画壁画。

=== 5. 里昂美食市场 (Halles de Lyon Paul Bocuse)

* *必吃理由* : 以传奇主厨命名的室内顶级美食天堂。
* *核心体验* : 寻找正宗的 *圣马塞兰奶酪 (Saint-Marcellin)*。

=== 6. 汇流博物馆 (Musée des Confluences)

* *必玩理由* : 位于两河交汇处，极具未来感的“水晶云”建筑。
* *核心体验* : https://www.museedesconfluences.fr[汇流博物馆 (Musée des Confluences)] 欣赏解构主义建筑。